export const EXPRESS_CASSANDRA_MODULE_OPTIONS =
  'EXPRESS_CASSANDRA_MODULE_OPTIONS';
export const EXPRESS_CASSANDRA_MODULE_ID = 'EXPRESS_CASSANDRA_MODULE_ID';
export const DEFAULT_CONNECTION_NAME = 'DefaultConnection';

export const ENTITY_METADATA = 'ENTITY_METADATA';
export const ENTITY_NAME_KEY = 'ENTITY_NAME_KEY';
export const ENTITY_OPTIONS_KEY = 'ENTITY_OPTIONS_KEY';
export const ENTITY_ATTRIBUTE_KEY = 'ENTITY_ATTRIBUTE_KEY';
