export const EXPRESS_CASSANDRA_MODULE_OPTIONS =
  'EXPRESS_CASSANDRA_MODULE_OPTIONS';
export const EXPRESS_CASSANDRA_MODULE_ID = 'EXPRESS_CASSANDRA_MODULE_ID';
export const DEFAULT_CONNECTION_NAME = 'DefaultConnection';
